site_name: 兌幣機雲服務系統專案
site_description: 兌幣機系統從LINE遷移至Telegram的完整解決方案
site_author: 兌幣機開發團隊
site_url: https://propsky.github.io/coinerEX

# Repository
repo_name: propsky/coinerEX
repo_url: https://github.com/propsky/coinerEX

# Navigation
nav:
  - 業務分析:
      - business/pricing-guide.md
      - business/customer-upgrade-guide.md
  - 技術規劃:
      - development/cloud-development.md
      - technical/telegram-ui-design.md
      - development/project-roadmap.md
  - MVP開發:
      - development/mvp-specification.md
      - development/mvp-todo-checklist.md
      - development/mvp-project-management.md

# Theme
theme:
  name: material
  language: zh-TW
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切換至深色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切換至淺色模式
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate

# Plugins
plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/coinerEX
  generator: false
  
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - javascripts/mermaid.js